name: Build and Release WashMoney

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        shell: cmd
        run: |
            pyinstaller --noconfirm --onefile --windowed ^
                --icon "icon.ico" ^
                --add-data "icon.ico;." ^
                main.py
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: washmoney-exe
          path: dist/main.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: washmoney-exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: WashMoney.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
